### ISSUE TITLE
how keep

### ISSUE THREAD

**Issue by leftchest** [TeXmeijin/vite-react-ts-tailwind-starter#2]
how keep it live on vercel 

1. to deploy the repo  on vercel , i did like this:
ROOT DIRECTORY: `./`
BUILD COMMAND: `npm run build`
OUTPUT DIRECTORY: `./dist`
then ,result is :Deployment failed

2. another repo also Powered by React, Tailwind CSS, Vite and TypeScript: [https://github.com/spencerwooo/portfolio-react](url)
to deploy the repo  on vercel , i did like this:
ROOT DIRECTORY: `./`
BUILD COMMAND: `npm run build`
OUTPUT DIRECTORY: `./dist`
then ,result is :Deployment success: [https://portfolio-index-1.vercel.app](url)
**but**, the page of projects reload (f5) is 404:  [https://portfolio-index-1.vercel.app/projects](url)
how can i fix it ? thanks for your help !

**Comment by TeXmeijin** [comment]
@leftchest 
Thanks for your report.
This error was caused by type error. 
So I updated `react-cool-dimensions` library then fixed type error.

I tried build and deploy at Vercel and the build was success. Please check it.
